[relaychain]
chain = "rococo-local"


[[relaychain.nodes]]
name = "validator-01"
validator = true

[[relaychain.nodes]]
name = "validator-02"
validator = true


[[parachains]]
id = 2000
default_command = "./target/release/bloc-node"

[[parachains.collators]]
name = "bloc-collator-01"
rpc_port = 9001
